name: API CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package -f CapstoneAPI/pom.xml
  test:
    name: Test API Automation
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Scenario and Test Case
        run: mvn clean verify -f CapstoneAPI/pom.xml
